#!/usr/bin/env bash
#
# Generate LiftMark/App/SentryConfig.swift from the Sentry DSN.
#
# Single source of truth for the generated config, invoked from two places:
#   1. The Xcode "Generate SentryConfig" build phase (project.yml), where
#      SENTRY_DSN_REST is exposed as an env var from Config/Sentry.xcconfig.
#   2. CI workflows and `make generate`, BEFORE `xcodegen generate` runs —
#      because xcodegen globs the source tree at project-generation time, the
#      (gitignored) SentryConfig.swift must already exist on disk or it won't
#      be added to the compile sources. The build phase then refreshes its
#      contents on every build.
#
# DSN resolution: $SENTRY_DSN_REST if set, else parsed out of
# Config/Sentry.xcconfig, else empty. An empty DSN is valid — CrashReporter
# no-ops, which is exactly what CI/PR builds want.
set -euo pipefail

ROOT="${SRCROOT:-$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)}"
XCCONFIG="${ROOT}/Config/Sentry.xcconfig"

REST="${SENTRY_DSN_REST:-}"
if [ -z "$REST" ] && [ -f "$XCCONFIG" ]; then
  # Take the last non-comment SENTRY_DSN_REST assignment; strip the key and
  # surrounding whitespace. Comment lines (`// …`) are skipped by the anchor.
  REST="$(grep -E '^[[:space:]]*SENTRY_DSN_REST[[:space:]]*=' "$XCCONFIG" \
            | tail -n1 | sed -E 's/^[^=]*=[[:space:]]*//' | tr -d '[:space:]')"
fi

if [ -n "$REST" ]; then
  DSN="https://${REST}"
else
  DSN=""
fi

mkdir -p "${ROOT}/LiftMark/App"
cat > "${ROOT}/LiftMark/App/SentryConfig.swift" <<SWIFT
// Auto-generated — do not edit. Source: Config/Sentry.xcconfig (SENTRY_DSN_REST).
// Regenerated by scripts/gen-sentry-config.sh (Xcode build phase + pre-xcodegen).
enum SentryConfig {
    static let dsn = "${DSN}"
}
SWIFT
